 
database:
  type: mssql
  host: DESKTOP-QMALRMM
  instance:   SQLEXPRESS # SQLEXPRESS
  port: 1433
  user: sa
  password: 2good2btrue
  dbname: email
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: localhost
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /Users/eric_/oneDrive/Desktop/bot

cmd:
  port: 9501
  host: localhost

http:
  port: 18083


allStart: 1
proxyEnable : true
